name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7.0' 
      - name: Convert yaml to json
        run: python .github/workflows/lib/yaml_to_json.py resources/referers.yml referers.json
      - name: Check
        run: ls
